version: '3.9'

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped

  flask_web:
    build: ./flask_web
    container_name: flask_web
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mosquitto
    restart: unless-stopped

  mqtt_listener:
    build: ./mqtt-listener
    container_name: mqtt_listener
    env_file:
      - .env
    depends_on:
      - mosquitto
    restart: unless-stopped
